### ISSUE TITLE
Zpool unavailable, __getstate__() returns KeyError: 'unsup_feat'

### ISSUE THREAD

**Issue by rcmcdonald91** [truenas/py-libzfs#144]
I'm using py-libzfs to output a large json dump of ZFS status... just libzfs.ZFS().___getstate___() out to json. This works great. However, I've hit a situation where a test zpool with a raidz1 with file-based vdevs is unavailable, .___getstate___() returns 'KeyError: 'unsup_feat'

```
>>> zfs = libzfs.ZFS().__getstate__()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "libzfs.pyx", line 417, in libzfs.ZFS.__getstate__
  File "libzfs.pyx", line 2435, in libzfs.ZFSPool.__getstate__
  File "libzfs.pyx", line 2656, in libzfs.ZFSPool.status_detail.__get__
  File "libzfs.pyx", line 2617, in libzfs.ZFSPool.__unsup_features
KeyError: 'unsup_feat'
```

The test zpool in question has a status code of ```PoolStatus.MISSING_DEV_NR``` , I would expect __getstate__() to still work even though one of the zpools is in a fault condition. In fact, getstate should always work and shouldn't fail like this

Any ideas what's going on here?

**Comment by rcmcdonald91** [comment]
Looks like this is probably a bug in libzfs.c, https://github.com/openzfs/zfs/blob/60ffc1c460e4cdf3c3ca12c8840fd0675a98ed0d/module/zfs/zfeature.c#L169, unsupported types are likely not being added to the nvlist


Or perhaps we need to check the existence of the key in the nvlist before trying to return it, which is really a proper use of nvlists

**Comment by rcmcdonald91** [comment]
Fix: https://github.com/truenas/py-libzfs/pull/145
